/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import {MirroredRepeatWrapping, MeshBasicMaterial, MeshStandardMaterial } from 'three';
import  {useFrame} from 'react-three-fiber'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Chair.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh material={materials.Material} geometry={nodes.Chair.geometry} scale={[1.04, 1.04, 1.04]} />
    </group>
  )
}

useGLTF.preload('/Chair.glb')
