/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'

import { useGLTF, useTexture } from '@react-three/drei'
import {useFrame} from 'react-three-fiber'
export default function Model(props) {

  const group = useRef()
  const { nodes, materials } = useGLTF('/Crate.glb');
  const crate = useRef();
    useFrame(() => {
    crate.current.rotation.x = crate.current.rotation.y += 0.01
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh ref={crate} material={materials.crate} geometry={nodes.crate.geometry} />
    </group>
  )
}

useGLTF.preload('/Crate.glb')
